services:
  db:
    image: postgres:15
    container_name: escalapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escalapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d escalapp"]
      interval: 5s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev   # (opcional, aquí ya usamos la última etapa que es dev)
    container_name: escalapp-web
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run db:seed &&
        npm run dev
      "

volumes:
  pgdata:
